# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ChaChaChat

on:
  push:
    branches:
      - buildOnAzure
  workflow_dispatch:

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: change server and dir
        run: |           
           sed -i 's/localhost/${{secrets.DEPLOYIP}}/g' ./frontend/src/app/websocket.service.ts

      - name: npm install, build,  lint and test
        run: |
          cd frontend
          npm install
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run lint --if-present
          npm run build --if-present
          
          
          
      - name: list files
        run: |
          pwd
          ls
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ChaChaChat'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B6A03CFDE7144533A889346CAA5E1E02 }}
          package: ./frontend/dist/frontend

