

name: Run tests

on: workflow_dispatch

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone supercharge website repository
      uses: actions/checkout@v2

    # This part here is cloning a second repository
    # While cloning the repository:
    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`
   # - name: Clone supercharge docs repository
   #   uses: actions/checkout@v2
   #   with:
    #    repository: https://r-n-d.informatik.hs-augsburg.de:8080/hof/chachachat.git
    #    token: ${{ secrets.RNDTOKEN }}
    #    path: otherbranches/priv
      #  ref: main
        
    - name: list
      run: |
        pwd
        ls
        mkdir otherbranches
        cd otherbranches
        git clone https://gitlab-ci-token:ksKqmNstvqCxLMbP124Q@r-n-d.informatik.hs-augsburg.de:8080/hof/chachachat
        ls
      

  
